/**
 * NAVMC 10132 derivation engine, barrel.
 *
 * Phase 2 of docs/NAVMC_10132_BUILD_PLAN.md. Every export here is a PURE
 * function with no React and no pdf-lib, because three behaviours on this form
 * are generated by PDF JavaScript that neither pdf-lib nor the app will ever
 * run, and each one produces a plausible-looking WRONG document when done by
 * hand. Isolating them behind tested functions is the whole point of the phase.
 *
 * The three, and what goes wrong without them:
 *
 *   bookerStatement / coerceDemand
 *     "2 BOOKER" looks like static artwork. It is rewritten by three identical
 *     on-blur handlers, and the blank ships with the ACCEPTANCE text stored. A
 *     fill of a refusal case would state that the accused accepted NJP.
 *
 *   renderPunishment
 *     Item 6 is free text on paper. Composing it from structured codes is what
 *     lets the export gate check ceilings and authority grade without parsing
 *     prose, and what lets the app measure the result against a 123-character
 *     field that clips silently.
 *
 *   composeRemarks / isPrescribedFormat
 *     Item 21 has ten prescribed formats required in chronological order. Free
 *     text alone guarantees format drift, which is what a legal review finds.
 *
 * The fourth module is not JavaScript-derived but belongs with them:
 *
 *   measureText / fitsInField / overflowBy
 *     Every widget is Arial 8pt and none auto-shrink, so overflow clips with no
 *     warning. Fit is a WIDTH question, not a character count. The field map's
 *     capacity figure is a UI meter hint only.
 *
 * Import from this barrel rather than the individual modules so the phase reads
 * as one engine at the call sites.
 */

export { bookerStatement, coerceDemand } from '@/lib/navmc10132-booker';

export {
  renderPunishment,
  Navmc10132PunishmentRenderError,
  type RenderPunishmentOptions,
  type Navmc10132PunishmentEntry,
} from '@/lib/navmc10132-punishment-render';

export {
  composeRemarks,
  isPrescribedFormat,
  type Navmc10132Remark,
  type Navmc10132RemarkKind,
} from '@/lib/navmc10132-remarks';

export {
  measureText,
  usableWidthOf,
  linesOf,
  fitsInField,
  overflowBy,
} from '@/lib/navmc10132-capacity';

// Re-exported so a call site needs one import for the whole engine.
export {
  resolveArticle,
  NAVMC_10132_ARTICLES,
  NAVMC_10132_ARTICLE_GROUPS,
  type Navmc10132Article,
} from '@/lib/navmc10132-articles';

export {
  resolvePunishment,
  authoritySatisfies,
  NAVMC_10132_PUNISHMENTS,
  NAVMC_10132_RELEASE_ONE_PUNISHMENTS,
  type Navmc10132Punishment,
  type PunishmentAppliesTo,
  type PunishmentAuthority,
  type PunishmentParameter,
} from '@/lib/navmc10132-punishments';

export {
  NAVMC_10132_FIELD_METRICS,
  type Navmc10132FieldMetric,
} from '@/lib/navmc10132-field-metrics';
