/**
 * NAVMC 10132 offense crosswalk: form dropdown label to MCTFS article code.
 *
 * GENERATED by tools/aa-forms/gen_navmc10132_articles.py from
 * tools/aa-forms/navmc10132-map.json plus the MCTFSPRIUM article code table.
 * Do not hand-edit. Regenerate and review the diff.
 *
 * `formLabel` is the /Opt EXPORT value of the five `1x ARTICLE` dropdowns and
 * must stay byte-exact, double spaces included. It is what the emitter writes
 * and what prints on the form.
 *
 * `mctfsCode` is what the unit diary needs. The relationship is MANY-TO-ONE:
 * 167 form labels collapse onto 113 codes. Twenty base articles collapse,
 * Art. 92 with 22 labels and Art. 134 with 25 being the largest.
 *
 * Two routing rules are not derivable from the strings and are encoded by hand
 * in the generator:
 *   - The two Art. 92 sexual-harassment labels route to 92.1, the other twenty
 *     to 92. Misrouting these misreports a sexual harassment case as an
 *     ordinary order violation.
 *   - Art. 134 maps to twenty sub-codes. Four General Article labels collapse
 *     to 134.91 and four drunk-and-disorderly labels to 134.98.
 *
 * Known gaps, documented in docs/NAVMC_10132_SPEC.md section 11.1: MCTFS codes
 * 78 (accessory after the fact) and 109A (mail matter) have NO form option and
 * the dropdown is not editable, so those offenses can only be recorded through
 * the item 21 additional-offenses remark.
 *
 * Rule source: docs/NAVMC_10132_SPEC.md sections 11.1 and 11.2.
 */

export interface Navmc10132Article {
  /** /Opt export value of the 1x ARTICLE dropdowns. Byte-exact. */
  formLabel: string;
  /** MCTFSPRIUM article code for unit diary reporting. */
  mctfsCode: string;
  /** Base UCMJ article, for grouping the picker. */
  articleNumber: string;
  /**
   * TRUE when the offense is ordinarily NOT a minor offense, so NJP is
   * questionable. MCM Part V para 1.e: a minor offense ordinarily carries no
   * dishonorable discharge and no confinement over one year at GCM.
   * Drives warning W-01. Never blocks - the decision belongs to the commander.
   */
  notOrdinarilyMinor: boolean;
}

export const NAVMC_10132_ARTICLES: readonly Navmc10132Article[] = [
  { formLabel: 'Art. 80  Attempts', mctfsCode: '80', articleNumber: '80', notOrdinarilyMinor: false },
  { formLabel: 'Art. 81  Conspiracy', mctfsCode: '81', articleNumber: '81', notOrdinarilyMinor: false },
  { formLabel: 'Art. 82  Soliciting commission of offenses', mctfsCode: '82', articleNumber: '82', notOrdinarilyMinor: false },
  { formLabel: 'Art. 83  Malingering', mctfsCode: '83', articleNumber: '83', notOrdinarilyMinor: false },
  { formLabel: 'Art. 83  Self-injury with intent to avoid service', mctfsCode: '83', articleNumber: '83', notOrdinarilyMinor: false },
  { formLabel: 'Art. 84  Breach of medical quarantine', mctfsCode: '84', articleNumber: '84', notOrdinarilyMinor: false },
  { formLabel: 'Art. 85  Desertion', mctfsCode: '85', articleNumber: '85', notOrdinarilyMinor: false },
  { formLabel: 'Art. 86  Absence without leave', mctfsCode: '86', articleNumber: '86', notOrdinarilyMinor: false },
  { formLabel: 'Art. 86  Absence without leave >30 days', mctfsCode: '86', articleNumber: '86', notOrdinarilyMinor: false },
  { formLabel: 'Art. 86  Absence (intent to abandon guard or watch)', mctfsCode: '86', articleNumber: '86', notOrdinarilyMinor: false },
  { formLabel: 'Art. 86  Absence (intent to avoid maneuvers or exercise)', mctfsCode: '86', articleNumber: '86', notOrdinarilyMinor: false },
  { formLabel: 'Art. 87  Missing movement', mctfsCode: '87', articleNumber: '87', notOrdinarilyMinor: false },
  { formLabel: 'Art. 87  Jumping from vessel', mctfsCode: '87', articleNumber: '87', notOrdinarilyMinor: false },
  { formLabel: 'Art. 87a  Resistance, flight, breach of arrest, and escape', mctfsCode: '87A', articleNumber: '87A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 87b  Escape/breach correctional custody', mctfsCode: '87B', articleNumber: '87B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 87b  Breach of restriction', mctfsCode: '87B', articleNumber: '87B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 88  Contempt toward officials', mctfsCode: '88', articleNumber: '88', notOrdinarilyMinor: false },
  { formLabel: 'Art. 89  Disrespect of sup. comm. officer', mctfsCode: '89', articleNumber: '89', notOrdinarilyMinor: false },
  { formLabel: 'Art. 89  Assault of sup. comm. officer', mctfsCode: '89', articleNumber: '89', notOrdinarilyMinor: false },
  { formLabel: 'Art. 90  Willfully disobeying sup. comm. officer', mctfsCode: '90', articleNumber: '90', notOrdinarilyMinor: false },
  { formLabel: 'Art. 91  Assault of WO/NCO', mctfsCode: '91', articleNumber: '91', notOrdinarilyMinor: false },
  { formLabel: 'Art. 91  Disobeying WO/NCO', mctfsCode: '91', articleNumber: '91', notOrdinarilyMinor: false },
  { formLabel: 'Art. 91  Disrespect toward WO/NCO', mctfsCode: '91', articleNumber: '91', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. MCO 5354.1 (series) (Harassment)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. MCO 5354.1 (series) (Bullying)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. MCO 5354.1 (series) (Hazing)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. MCO 5354.1 (series) (Unlawful Discrimination)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. MCO 5354.1 (series) (Sexual Harassment)', mctfsCode: '92.1', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. MCO 5354.1 (series) (Dissident Activity)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. MCO 5354.1 (series) (Wrongful Distribution of Intimate Images)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. SECNAVINST 5300.28 (series) (Controlled Substance)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. SECNAVINST 5300.28 (series) (OTC Substance)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. SECNAVINST 5300.28 (series) (Natural Substance)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. SECNAVINST 5300.28 (series) (Paraphernalia)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. USNR 1165 (Fraternization)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. USNR 1166 (Sexual Harassment)', mctfsCode: '92.1', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. USNR 1167 (Supremacist Activities)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. USNR 1168 (Intimate Images)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. ALNAV 074/20 (Hemp Use)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. DoDI 1325.06 (Extremism/Protest)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Viol. DoDI 1344.10 (Political Activities)', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Failure to obey general order or regulation', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Failure to obey other order or regulation', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Dereliction of duty by neglect', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 92  Willful dereliction of duty', mctfsCode: '92', articleNumber: '92', notOrdinarilyMinor: false },
  { formLabel: 'Art. 93  Cruelty and maltreatment', mctfsCode: '93', articleNumber: '93', notOrdinarilyMinor: false },
  { formLabel: 'Art. 93a  Prohibited activities with recruit or trainee', mctfsCode: '93A', articleNumber: '93A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 94  Mutiny or sedition', mctfsCode: '94', articleNumber: '94', notOrdinarilyMinor: true },
  { formLabel: 'Art. 95  Drunk on post', mctfsCode: '95', articleNumber: '95', notOrdinarilyMinor: false },
  { formLabel: 'Art. 95  Sleeping on post', mctfsCode: '95', articleNumber: '95', notOrdinarilyMinor: false },
  { formLabel: 'Art. 95  Loitering by post', mctfsCode: '95', articleNumber: '95', notOrdinarilyMinor: false },
  { formLabel: 'Art. 95a  Disrespect towards sentinel or lookout', mctfsCode: '95A', articleNumber: '95A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 96  Release of prisoner without authority', mctfsCode: '96', articleNumber: '96', notOrdinarilyMinor: false },
  { formLabel: 'Art. 96  Drinking with prisoner', mctfsCode: '96', articleNumber: '96', notOrdinarilyMinor: false },
  { formLabel: 'Art. 97  Unlawful detention', mctfsCode: '97', articleNumber: '97', notOrdinarilyMinor: false },
  { formLabel: 'Art. 98  Misconduct as prisoner', mctfsCode: '98', articleNumber: '98', notOrdinarilyMinor: false },
  { formLabel: 'Art. 99  Misbehavior before enemy', mctfsCode: '99', articleNumber: '99', notOrdinarilyMinor: true },
  { formLabel: 'Art. 100  Subordinate compelling surrender', mctfsCode: '100', articleNumber: '100', notOrdinarilyMinor: false },
  { formLabel: 'Art. 101  Improper use of countersign', mctfsCode: '101', articleNumber: '101', notOrdinarilyMinor: false },
  { formLabel: 'Art. 102  Forcing a safeguard', mctfsCode: '102', articleNumber: '102', notOrdinarilyMinor: false },
  { formLabel: 'Art. 103  Spies', mctfsCode: '103', articleNumber: '103', notOrdinarilyMinor: false },
  { formLabel: 'Art. 103a  Espionage', mctfsCode: '103A', articleNumber: '103A', notOrdinarilyMinor: true },
  { formLabel: 'Art. 103b  Aiding the enemy', mctfsCode: '103B', articleNumber: '103B', notOrdinarilyMinor: true },
  { formLabel: 'Art. 104  Public records offenses', mctfsCode: '104', articleNumber: '104', notOrdinarilyMinor: false },
  { formLabel: 'Art. 104a  Fraudulent enlistment, appointment, or separation', mctfsCode: '104A', articleNumber: '104A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 104b  Unlawful enlistment, appointment, or separation', mctfsCode: '104B', articleNumber: '104B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 105  Forgery', mctfsCode: '105', articleNumber: '105', notOrdinarilyMinor: false },
  { formLabel: 'Art. 105a  False or unauthorized pass offenses', mctfsCode: '105A', articleNumber: '105A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 106  Impersonation', mctfsCode: '106', articleNumber: '106', notOrdinarilyMinor: false },
  { formLabel: 'Art. 106a  Wearing unauthorized insignia', mctfsCode: '106A', articleNumber: '106A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 107  False official statements', mctfsCode: '107', articleNumber: '107', notOrdinarilyMinor: false },
  { formLabel: 'Art. 107  False swearing', mctfsCode: '107', articleNumber: '107', notOrdinarilyMinor: false },
  { formLabel: 'Art. 107a  Parole violation', mctfsCode: '107A', articleNumber: '107A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 108  Selling military property', mctfsCode: '108', articleNumber: '108', notOrdinarilyMinor: false },
  { formLabel: 'Art. 108  Selling military property (firearm/explosive)', mctfsCode: '108', articleNumber: '108', notOrdinarilyMinor: false },
  { formLabel: 'Art. 108  Damaging, etc., military property by neglect ≤ $1000', mctfsCode: '108', articleNumber: '108', notOrdinarilyMinor: false },
  { formLabel: 'Art. 108  Damaging, etc., military property by neglect > $1000', mctfsCode: '108', articleNumber: '108', notOrdinarilyMinor: false },
  { formLabel: 'Art. 108  Damaging, etc., military property willfully', mctfsCode: '108', articleNumber: '108', notOrdinarilyMinor: false },
  { formLabel: 'Art. 108a  Captured or abandoned property', mctfsCode: '108A', articleNumber: '108A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 108a  Looting or pillaging', mctfsCode: '108A', articleNumber: '108A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 109  Waste, spoilage, destruction of other property', mctfsCode: '109', articleNumber: '109', notOrdinarilyMinor: false },
  { formLabel: 'Art. 110  Improper hazarding of vessel or aircraft', mctfsCode: '110', articleNumber: '110', notOrdinarilyMinor: false },
  { formLabel: 'Art. 111  Leaving scene of vehicle accident', mctfsCode: '111', articleNumber: '111', notOrdinarilyMinor: false },
  { formLabel: 'Art. 112  Drunk on duty', mctfsCode: '112', articleNumber: '112', notOrdinarilyMinor: false },
  { formLabel: 'Art. 112  Drunkenness and other incapacitation', mctfsCode: '112', articleNumber: '112', notOrdinarilyMinor: false },
  { formLabel: 'Art. 112a  Wrongful use, possession, etc. of controlled substances', mctfsCode: '112A', articleNumber: '112A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 113  Drunken or reckless operation of vehicle, aircraft, or vessel', mctfsCode: '113', articleNumber: '113', notOrdinarilyMinor: false },
  { formLabel: 'Art. 114  Endangerment offenses', mctfsCode: '114', articleNumber: '114', notOrdinarilyMinor: false },
  { formLabel: 'Art. 115  Communicating threats', mctfsCode: '115', articleNumber: '115', notOrdinarilyMinor: false },
  { formLabel: 'Art. 116  Riot', mctfsCode: '116', articleNumber: '116', notOrdinarilyMinor: false },
  { formLabel: 'Art. 116  Breach of peace', mctfsCode: '116', articleNumber: '116', notOrdinarilyMinor: false },
  { formLabel: 'Art. 117  Provoking speeches or gestures', mctfsCode: '117', articleNumber: '117', notOrdinarilyMinor: false },
  { formLabel: 'Art. 117a  Wrongful broadcast or distribution of intimate visual image', mctfsCode: '117A', articleNumber: '117A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 118  Murder', mctfsCode: '118', articleNumber: '118', notOrdinarilyMinor: true },
  { formLabel: 'Art. 119  Manslaughter', mctfsCode: '119', articleNumber: '119', notOrdinarilyMinor: true },
  { formLabel: 'Art. 119a  Death of unborn child', mctfsCode: '119A', articleNumber: '119A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 119a  Injury of unborn child', mctfsCode: '119A', articleNumber: '119A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 119b  Child endangerment', mctfsCode: '119B', articleNumber: '119B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 120  Rape and sexual assault', mctfsCode: '120', articleNumber: '120', notOrdinarilyMinor: true },
  { formLabel: 'Art. 120  Sexual assault', mctfsCode: '120', articleNumber: '120', notOrdinarilyMinor: true },
  { formLabel: 'Art. 120  Aggravated sexual contact', mctfsCode: '120', articleNumber: '120', notOrdinarilyMinor: true },
  { formLabel: 'Art. 120  Abusive sexual contact', mctfsCode: '120', articleNumber: '120', notOrdinarilyMinor: true },
  { formLabel: 'Art. 120a  Mail deposit of obscene matter', mctfsCode: '120A', articleNumber: '120A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 120b  Rape of a child', mctfsCode: '120B', articleNumber: '120B', notOrdinarilyMinor: true },
  { formLabel: 'Art. 120b  Sexual assault of a child', mctfsCode: '120B', articleNumber: '120B', notOrdinarilyMinor: true },
  { formLabel: 'Art. 120b  Sexual abuse of a child', mctfsCode: '120B', articleNumber: '120B', notOrdinarilyMinor: true },
  { formLabel: 'Art. 120c  Indecent viewing', mctfsCode: '120C', articleNumber: '120C', notOrdinarilyMinor: false },
  { formLabel: 'Art. 120c  Indecent recording', mctfsCode: '120C', articleNumber: '120C', notOrdinarilyMinor: false },
  { formLabel: 'Art. 120c  Distribution of indecent recording', mctfsCode: '120C', articleNumber: '120C', notOrdinarilyMinor: false },
  { formLabel: 'Art. 120c  Forcible pandering', mctfsCode: '120C', articleNumber: '120C', notOrdinarilyMinor: false },
  { formLabel: 'Art. 120c  Indecent exposure', mctfsCode: '120C', articleNumber: '120C', notOrdinarilyMinor: false },
  { formLabel: 'Art. 121  Larceny and wrongful appropriation', mctfsCode: '121', articleNumber: '121', notOrdinarilyMinor: false },
  { formLabel: 'Art. 121a  Fraudulent use of credit cards, etc.', mctfsCode: '121A', articleNumber: '121A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 121b  False pretenses to obtain services', mctfsCode: '121B', articleNumber: '121B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 122  Robbery', mctfsCode: '122', articleNumber: '122', notOrdinarilyMinor: true },
  { formLabel: 'Art. 122a  Receiving stolen property', mctfsCode: '122A', articleNumber: '122A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 123  Offenses concerning government computers', mctfsCode: '123', articleNumber: '123', notOrdinarilyMinor: false },
  { formLabel: 'Art. 123a  Check without sufficient funds (fraudulent intent)', mctfsCode: '123A', articleNumber: '123A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 124  Frauds against the United States', mctfsCode: '124', articleNumber: '124', notOrdinarilyMinor: false },
  { formLabel: 'Art. 124a  Bribery', mctfsCode: '124A', articleNumber: '124A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 124b  Graft', mctfsCode: '124B', articleNumber: '124B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 125  Kidnapping', mctfsCode: '125', articleNumber: '125', notOrdinarilyMinor: true },
  { formLabel: 'Art. 126  Arson', mctfsCode: '126', articleNumber: '126', notOrdinarilyMinor: true },
  { formLabel: 'Art. 126  Burning property with intent to defraud', mctfsCode: '126', articleNumber: '126', notOrdinarilyMinor: true },
  { formLabel: 'Art. 127  Extortion', mctfsCode: '127', articleNumber: '127', notOrdinarilyMinor: false },
  { formLabel: 'Art. 128  Simple assault (no battery, no weapon)', mctfsCode: '128', articleNumber: '128', notOrdinarilyMinor: false },
  { formLabel: 'Art. 128  Assault', mctfsCode: '128', articleNumber: '128', notOrdinarilyMinor: false },
  { formLabel: 'Art. 128a  Maiming', mctfsCode: '128A', articleNumber: '128A', notOrdinarilyMinor: true },
  { formLabel: 'Art. 128b  Domestic violence', mctfsCode: '128B', articleNumber: '128B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 129  Burglary', mctfsCode: '129', articleNumber: '129', notOrdinarilyMinor: false },
  { formLabel: 'Art. 129  Unlawful entry', mctfsCode: '129', articleNumber: '129', notOrdinarilyMinor: false },
  { formLabel: 'Art. 130  Stalking', mctfsCode: '130', articleNumber: '130', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131  Perjury', mctfsCode: '131', articleNumber: '131', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131a  Subornation of perjury', mctfsCode: '131A', articleNumber: '131A', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131b  Obstruction of justice', mctfsCode: '131B', articleNumber: '131B', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131c  Misprision of serious offense', mctfsCode: '131C', articleNumber: '131C', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131d  Wrongful refusal to testify', mctfsCode: '131D', articleNumber: '131D', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131e  Prevention of authorized seizure of property', mctfsCode: '131E', articleNumber: '131E', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131f  Noncompliance with procedural rules', mctfsCode: '131F', articleNumber: '131F', notOrdinarilyMinor: false },
  { formLabel: 'Art. 131g  Wrongful interference with adverse administrative proceedings', mctfsCode: '131G', articleNumber: '131G', notOrdinarilyMinor: false },
  { formLabel: 'Art. 132  Retaliation', mctfsCode: '132', articleNumber: '132', notOrdinarilyMinor: false },
  { formLabel: 'Art. 133  Conduct unbecoming an officer', mctfsCode: '133', articleNumber: '133', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  General Article', mctfsCode: '134.91', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  General Article Clause 1', mctfsCode: '134.91', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  General Article Clause 2', mctfsCode: '134.91', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  General Article Clause 3', mctfsCode: '134.91', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Animal abuse', mctfsCode: '134.92', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Bigamy', mctfsCode: '134.93', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Worthless check (bad faith in maintaining funds)', mctfsCode: '134.94', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Child pornography', mctfsCode: '134.95', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Dishonorably failing to pay debt', mctfsCode: '134.96', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Disloyal statements', mctfsCode: '134.97', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Disorderly conduct', mctfsCode: '134.98', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Drunk and disorderly conduct', mctfsCode: '134.98', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Drunk and disorderly conduct aboard ship', mctfsCode: '134.98', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Drunkenness', mctfsCode: '134.98', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Extramarital sexual conduct', mctfsCode: '134.99', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Negligent discharge of firearm', mctfsCode: '134.100', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Fraternization', mctfsCode: '134.101', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Gambling with subordinate', mctfsCode: '134.102', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Negligent homicide', mctfsCode: '134.103', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Indecent conduct', mctfsCode: '134.104', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Indecent language', mctfsCode: '134.105', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Pandering and prostitution', mctfsCode: '134.106', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Self-injury without intent to avoid service', mctfsCode: '134.107', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Sexual harassment', mctfsCode: '134.110', articleNumber: '134', notOrdinarilyMinor: false },
  { formLabel: 'Art. 134  Straggling', mctfsCode: '134.108', articleNumber: '134', notOrdinarilyMinor: false },
] as const;

/** Lookup by the form's own export value. */
const BY_LABEL = new Map<string, Navmc10132Article>(
  NAVMC_10132_ARTICLES.map((a) => [a.formLabel, a])
);

/**
 * Resolve a form dropdown label to its crosswalk row.
 * Returns undefined for an unknown label, which the emitter treats as an error
 * rather than guessing - the dropdown is a closed list.
 */
export function resolveArticle(formLabel: string): Navmc10132Article | undefined {
  return BY_LABEL.get(formLabel);
}

/** Base article numbers in the order the picker should group them. */
export const NAVMC_10132_ARTICLE_GROUPS: readonly string[] = Array.from(
  new Set(NAVMC_10132_ARTICLES.map((a) => a.articleNumber))
);

