import { DocumentTypeDefinition } from '@/lib/schemas';
import { ITypeSchema } from '@/lib/schemas/i-type-schema';
import { I_TYPE_OPTIONS } from '@/lib/i-type-options';

export const ITypeDefinition: DocumentTypeDefinition = {
  id: 'i-type',
  name: 'I-Type (Technical Publication)',
  description: 'USMC instruction sheet for technical publications and equipment documentation.',
  icon: '📋',
  schema: ITypeSchema,
  features: {
    showHeaderSettings: false,
    showFontSelector: false,
    showUnitInfo: false,
    showEndorsementDetails: false,
    showDirectiveTitle: false,
    showVia: false,
    showReferences: false,
    showEnclosures: false,
    showDistribution: false,
    showReports: false,
    showParagraphs: false,
    showClosingBlock: false,
    showMOAForm: false,
    showSignature: true,
    showDecisionGrid: false,
    showCoordinationTable: false,
    isAMHS: false,
    isDirective: false,
    showMultipleTo: false,
    showToDistribution: false,
    category: 'forms',
    exportFormats: ['pdf', 'docx'],
    pdfPipeline: 'standard',
  },
  sections: [
    {
      id: 'header',
      title: 'Publication Header',
      description: 'Identify the service, entity, and publication details.',
      fields: [
        {
          name: 'date',
          label: 'Date',
          type: 'date',
          required: true,
          className: 'md:col-span-1',
        },
        {
          name: 'shortTitle',
          label: 'Short Title',
          type: 'select',
          options: I_TYPE_OPTIONS.shortTitleFormats,
          required: true,
          className: 'md:col-span-1',
        },
        {
          name: 'volume',
          label: 'Volume (e.g., "1 OF 3")',
          type: 'text',
          placeholder: 'Optional: volume number',
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'service',
          label: 'Service',
          type: 'select',
          options: I_TYPE_OPTIONS.services,
          required: true,
          className: 'md:col-span-1',
        },
        {
          name: 'entity',
          label: 'Entity',
          type: 'select',
          options: I_TYPE_OPTIONS.entities,
          required: true,
          className: 'md:col-span-1',
        },
        {
          name: 'address',
          label: 'Address',
          type: 'select',
          options: I_TYPE_OPTIONS.addresses,
          required: false,
          className: 'col-span-full',
        },
      ],
    },
    {
      id: 'publication',
      title: 'Publication Information',
      description: 'Define the publication type, title, and nomenclature.',
      fields: [
        {
          name: 'publicationType',
          label: 'Publication Type',
          type: 'select',
          options: I_TYPE_OPTIONS.publicationTypes,
          required: true,
          className: 'col-span-full',
        },
        {
          name: 'longTitle',
          label: 'Long Title',
          type: 'text',
          placeholder: 'Full title of publication',
          required: true,
          className: 'col-span-full',
        },
        {
          name: 'category',
          label: 'Category',
          type: 'select',
          options: I_TYPE_OPTIONS.categories,
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'timeCompliance',
          label: 'Time Compliance',
          type: 'select',
          options: I_TYPE_OPTIONS.timeCompliance,
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'nomenclature',
          label: 'Nomenclature',
          type: 'text',
          placeholder: 'Equipment nomenclature',
          required: false,
          className: 'col-span-full',
        },
        {
          name: 'poc',
          label: 'Point of Contact (Phone/Email)',
          type: 'text',
          placeholder: 'POC phone number or email address',
          required: false,
          className: 'col-span-full',
        },
        {
          name: 'pcn',
          label: 'PCN (Product Control Number)',
          type: 'text',
          placeholder: 'PCN ### ###### ##',
          required: false,
          className: 'md:col-span-1',
        },
      ],
    },
    {
      id: 'distribution',
      title: 'Distribution & Control',
      description: 'Set signature authority, controlling office, and distribution parameters.',
      fields: [
        {
          name: 'signingAuthority',
          label: 'Signing Authority',
          type: 'select',
          options: I_TYPE_OPTIONS.signingAuthorities,
          required: true,
          className: 'md:col-span-1',
        },
        {
          name: 'controllingOffice',
          label: 'Controlling Office',
          type: 'select',
          options: I_TYPE_OPTIONS.controllingOffices,
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'cuiCategory',
          label: 'CUI Category',
          type: 'select',
          options: I_TYPE_OPTIONS.cuiCategories,
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'distributionControl',
          label: 'Control',
          type: 'select',
          options: I_TYPE_OPTIONS.controlMarkings,
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'supersedureNotice',
          label: 'Supersedure Notice',
          type: 'select',
          options: I_TYPE_OPTIONS.supersedureNotice,
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'supersedureStatement',
          label: 'Supersedure Statement',
          type: 'select',
          options: I_TYPE_OPTIONS.supersedureStatements,
          required: false,
          className: 'col-span-full',
        },
        {
          name: 'destructionNotice',
          label: 'Destruction Notice',
          type: 'select',
          options: I_TYPE_OPTIONS.destructionNotice,
          required: false,
          className: 'md:col-span-1',
        },
        {
          name: 'classificationDestructionProcedure',
          label: 'Classification Destruction Procedure',
          type: 'select',
          options: I_TYPE_OPTIONS.classificationDestructionProcedures,
          required: false,
          className: 'col-span-full',
        },
        {
          name: 'miStatement',
          label: 'MI Statement (Select for MIs)',
          type: 'select',
          options: I_TYPE_OPTIONS.miStatements,
          required: false,
          className: 'col-span-full',
        },
      ],
    },
  ],
};
