#!/usr/bin/env python3
"""Generate src/lib/navmc10132-articles.ts from the field map plus the
MCTFSPRIUM article code table.

Generated, not hand-written: 167 rows transcribed by hand would carry typos,
and the form labels contain double spaces after the article number that must
survive byte-exact because they ARE the /Opt export values.
"""
import json, re, sys

MAP = json.load(open(sys.argv[1] if len(sys.argv) > 1 else 'navmc10132-map.json'))

FORM_LABELS = None
for f in MAP['fields']:
    if f['name'] == '1A ARTICLE':
        FORM_LABELS = [o for o in f['exportValues'] if o.strip()]
assert FORM_LABELS and len(FORM_LABELS) == 167, len(FORM_LABELS or [])

# Art 134 form label -> MCTFS sub-code. Explicit because the collapse is
# many-to-one and not derivable from the strings.
ART_134 = {
    'Art. 134  General Article': '134.91',
    'Art. 134  General Article Clause 1': '134.91',
    'Art. 134  General Article Clause 2': '134.91',
    'Art. 134  General Article Clause 3': '134.91',
    'Art. 134  Animal abuse': '134.92',
    'Art. 134  Bigamy': '134.93',
    'Art. 134  Worthless check (bad faith in maintaining funds)': '134.94',
    'Art. 134  Child pornography': '134.95',
    'Art. 134  Dishonorably failing to pay debt': '134.96',
    'Art. 134  Disloyal statements': '134.97',
    'Art. 134  Disorderly conduct': '134.98',
    'Art. 134  Drunk and disorderly conduct': '134.98',
    'Art. 134  Drunk and disorderly conduct aboard ship': '134.98',
    'Art. 134  Drunkenness': '134.98',
    'Art. 134  Extramarital sexual conduct': '134.99',
    'Art. 134  Negligent discharge of firearm': '134.100',
    'Art. 134  Fraternization': '134.101',
    'Art. 134  Gambling with subordinate': '134.102',
    'Art. 134  Negligent homicide': '134.103',
    'Art. 134  Indecent conduct': '134.104',
    'Art. 134  Indecent language': '134.105',
    'Art. 134  Pandering and prostitution': '134.106',
    'Art. 134  Self-injury without intent to avoid service': '134.107',
    'Art. 134  Straggling': '134.108',
    'Art. 134  Sexual harassment': '134.110',
}

# Art 92 sexual-harassment labels route to 92.1. Every other Art 92 label
# routes to 92. Getting this wrong misreports a sexual harassment case as an
# ordinary order violation, which is a reportable-category error.
ART_92_SEXUAL_HARASSMENT = {
    'Art. 92  Viol. MCO 5354.1 (series) (Sexual Harassment)',
    'Art. 92  Viol. USNR 1166 (Sexual Harassment)',
}

# Offenses whose GCM maximum ordinarily includes a dishonorable discharge or
# confinement over one year, so they are ordinarily NOT minor offenses and NJP
# is questionable. MCM Part V para 1.e. Warning only, never a block.
NOT_ORDINARILY_MINOR = {
    '94', '99', '103A', '103B', '118', '119', '120', '120B',
    '122', '125', '126', '128A',
}

def base_article(label):
    m = re.match(r'Art\.\s+(\d+[a-zA-Z]?)\s', label)
    assert m, label
    return m.group(1).upper()

rows = []
for label in FORM_LABELS:
    art = base_article(label)
    if art == '134':
        code = ART_134[label]
    elif art == '92':
        code = '92.1' if label in ART_92_SEXUAL_HARASSMENT else '92'
    else:
        code = art
    rows.append((label, code, art, art in NOT_ORDINARILY_MINOR))

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")

out = []
out.append("""/**
 * NAVMC 10132 offense crosswalk: form dropdown label to MCTFS article code.
 *
 * GENERATED by tools/aa-forms/gen_navmc10132_articles.py from
 * tools/aa-forms/navmc10132-map.json plus the MCTFSPRIUM article code table.
 * Do not hand-edit. Regenerate and review the diff.
 *
 * `formLabel` is the /Opt EXPORT value of the five `1x ARTICLE` dropdowns and
 * must stay byte-exact, double spaces included. It is what the emitter writes
 * and what prints on the form.
 *
 * `mctfsCode` is what the unit diary needs. The relationship is MANY-TO-ONE:
 * 167 form labels collapse onto 113 codes. Twenty base articles collapse,
 * Art. 92 with 22 labels and Art. 134 with 25 being the largest.
 *
 * Two routing rules are not derivable from the strings and are encoded by hand
 * in the generator:
 *   - The two Art. 92 sexual-harassment labels route to 92.1, the other twenty
 *     to 92. Misrouting these misreports a sexual harassment case as an
 *     ordinary order violation.
 *   - Art. 134 maps to twenty sub-codes. Four General Article labels collapse
 *     to 134.91 and four drunk-and-disorderly labels to 134.98.
 *
 * Known gaps, documented in docs/NAVMC_10132_SPEC.md section 11.1: MCTFS codes
 * 78 (accessory after the fact) and 109A (mail matter) have NO form option and
 * the dropdown is not editable, so those offenses can only be recorded through
 * the item 21 additional-offenses remark.
 *
 * Rule source: docs/NAVMC_10132_SPEC.md sections 11.1 and 11.2.
 */

export interface Navmc10132Article {
  /** /Opt export value of the 1x ARTICLE dropdowns. Byte-exact. */
  formLabel: string;
  /** MCTFSPRIUM article code for unit diary reporting. */
  mctfsCode: string;
  /** Base UCMJ article, for grouping the picker. */
  articleNumber: string;
  /**
   * TRUE when the offense is ordinarily NOT a minor offense, so NJP is
   * questionable. MCM Part V para 1.e: a minor offense ordinarily carries no
   * dishonorable discharge and no confinement over one year at GCM.
   * Drives warning W-01. Never blocks - the decision belongs to the commander.
   */
  notOrdinarilyMinor: boolean;
}

export const NAVMC_10132_ARTICLES: readonly Navmc10132Article[] = [""")

for label, code, art, risk in rows:
    out.append(
        f"  {{ formLabel: '{esc(label)}', mctfsCode: '{code}', "
        f"articleNumber: '{art}', notOrdinarilyMinor: {str(risk).lower()} }},"
    )

out.append("""] as const;

/** Lookup by the form's own export value. */
const BY_LABEL = new Map<string, Navmc10132Article>(
  NAVMC_10132_ARTICLES.map((a) => [a.formLabel, a])
);

/**
 * Resolve a form dropdown label to its crosswalk row.
 * Returns undefined for an unknown label, which the emitter treats as an error
 * rather than guessing - the dropdown is a closed list.
 */
export function resolveArticle(formLabel: string): Navmc10132Article | undefined {
  return BY_LABEL.get(formLabel);
}

/** Base article numbers in the order the picker should group them. */
export const NAVMC_10132_ARTICLE_GROUPS: readonly string[] = Array.from(
  new Set(NAVMC_10132_ARTICLES.map((a) => a.articleNumber))
);
""")

sys.stdout.write('\n'.join(out) + '\n')
