#!/usr/bin/env python3
"""Emit src/lib/jagman-appendix-a1.ts from jagman-a1.json.

GENERATED CODE. The point of splitting extraction from generation is that the
verbatim appendix text never passes through a hand edit. This script copies
strings and adds types. It composes no prose of its own.

The text is fixed width. pdftotext -layout preserved the appendix's own column
alignment, and the underscore rules only line up when rendered in a monospace
face. Any renderer must use one.

Usage: python gen_jagman_a1.py jagman-a1.json -o ../../src/lib/jagman-appendix-a1.ts
"""
import argparse
import json
from pathlib import Path

HEADER = '''/**
 * JAGMAN Appendix A-1 forms, VERBATIM.
 *
 * GENERATED by tools/aa-forms/gen_jagman_a1.py from tools/aa-forms/jagman-a1.json,
 * which tools/aa-forms/extract_jagman_a1.py produced from the instruction PDF.
 * DO NOT EDIT BY HAND. Re-run the pair instead.
 *
 * These are rights advisements and a hearing script. A single reworded sentence
 * is a defect on a legal record, so no code outside the extractor is permitted
 * to author, paraphrase, reflow, or "clean up" this text. Callers fill the
 * blanks the appendix already provides and change nothing else.
 *
 * Source: {instruction} {change}, {changeDate}.
 * CH-2 removed and reissued pages A-1-a through A-1-q in full, so it controls
 * every appendix here regardless of what CH-1 said.
 * Source PDF SHA-256: {sha256}
 *
 * LETTERING WARNING. CH-2 shifted the front of the series. MCO 5800.16 Vol 14
 * para 010701 still cites "A-l-b, A-l-c, and A-l-d" for the accused's rights.
 * Under CH-2, A-1-b is the Letter of Instruction sample and is NOT a rights
 * form. There are two rights appendices, A-1-c and A-1-d, split solely on
 * whether the vessel exception applies. See docs/NJP_PACKAGE_RESEARCH.md 0.2.
 *
 * The text is FIXED WIDTH. Render it in a monospace face or the underscore
 * rules and the CO/ACC/WIT column will not line up.
 */

/** One appendix, as printed. */
export interface JagmanAppendix {{
  /** e.g. 'A-1-f'. Cite this, never a page number. */
  designator: string;
  /** The appendix's own heading, upper case as printed. */
  title: string;
  /** Plain-language description. Authored here, never printed. */
  description: string;
  /** Verbatim lines with page furniture removed. Nothing else altered. */
  text: readonly string[];
}}

/** Provenance for the citation string and for re-extraction. */
export const JAGMAN_A1_SOURCE = {{
  instruction: '{instruction}',
  change: '{change}',
  changeDate: '{changeDate}',
  sha256: '{sha256}',
}} as const;

/** Cite an appendix the way the JAGMAN and the MCO do. */
export function jagmanCitation(designator: string): string {{
  return `${{JAGMAN_A1_SOURCE.instruction}} ${{JAGMAN_A1_SOURCE.change}}, Appendix ${{designator}}`;
}}
'''


def ts_string(s: str) -> str:
    out = s.replace('\\', '\\\\').replace("'", "\\'")
    return f"'{out}'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('json', type=Path)
    ap.add_argument('-o', '--out', type=Path, required=True)
    args = ap.parse_args()

    data = json.loads(args.json.read_text(encoding='utf-8'))
    src = data['source']

    parts = [HEADER.format(**src)]

    for tag, entry in data['appendices'].items():
        const = 'APPENDIX_' + tag.replace('-', '_').upper()
        parts.append(f"\n/** {entry['description']}. */")
        parts.append(f'export const {const}: JagmanAppendix = {{')
        parts.append(f"  designator: {ts_string(entry['designator'])},")
        parts.append(f"  title: {ts_string(entry['title'] or '')},")
        parts.append(f"  description: {ts_string(entry['description'])},")
        parts.append('  text: [')
        for line in entry['text']:
            parts.append(f'    {ts_string(line)},')
        parts.append('  ],')
        parts.append('};')

    names = [(t, 'APPENDIX_' + t.replace('-', '_').upper())
             for t in data['appendices']]
    parts.append('\n/** Every extracted appendix, keyed by designator. */')
    parts.append('export const JAGMAN_A1: Readonly<Record<string, JagmanAppendix>> = {')
    for tag, const in names:
        parts.append(f'  {ts_string(tag)}: {const},')
    parts.append('};')
    parts.append('')

    args.out.write_text('\n'.join(parts), encoding='utf-8')
    total = sum(len(e['text']) for e in data['appendices'].values())
    print(f'wrote {args.out}')
    print(f'  {len(names)} appendices, {total} verbatim lines')


if __name__ == '__main__':
    main()
